---
- name: Ensure required packages are installed
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ 'git' | community.general.pkg_mgr | list }}"
  become: true

- name: Add Node.js repository for Debian/Ubuntu
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Add Node.js repo for RedHat-based systems
  shell: "curl -fsSL https://rpm.nodesource.com/setup_{{ nodejs_version }} | bash -"
  args:
    executable: /bin/bash
  when: ansible_os_family == "RedHat"
  become: true

- name: Install Node.js
  package:
    name: nodejs
    state: present
  become: true

- name: Clone quiz-ansible repository
  git:
    repo: "{{ quiz_repo_url }}"
    dest: "{{ quiz_app_dir }}"
    version: HEAD
  become: true

- name: Install Node dependencies
  npm:
    path: "{{ quiz_app_dir }}"
  become: true

- name: Build application
  command: npm run build
  args:
    chdir: "{{ quiz_app_dir }}"
  become: true

- name: Install serve globally
  npm:
    name: serve
    global: yes
  become: true

- name: Run the application
  shell: "nohup serve -s dist &"
  args:
    chdir: "{{ quiz_app_dir }}"
    executable: /bin/bash
  become: true

